version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: eshopper-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"

volumes:
  db:
